

-- TRANSACCIONAL CMR
DROP TABLE CAS_TRXCMR_12M;
CREATE TABLE CAS_TRXCMR_12M AS                                                           
SELECT B.RUT
, B.FECHA
, SUM(CASE WHEN FECHA_COMPRA BETWEEN B.FECHA_COMPRA-365 AND B.FECHA_COMPRA THEN A.MONTO_LIQUID_E ELSE 0 END) AS GASTO_CMR_12M
, SUM(CASE WHEN FECHA_COMPRA BETWEEN B.FECHA_COMPRA-180 AND B.FECHA_COMPRA THEN A.MONTO_LIQUID_E ELSE 0 END) AS GASTO_CMR_6M
FROM TMP_CAMADA B
LEFT JOIN DMCLTEPR.LK_DMC_CLIENTE C ON B.RUT=C.NUM_RUT
LEFT JOIN DMCLTEPR.FT_DMC_BOL_EMPRESAS A ON C.ID_DMC_CLIENTE=A.ID_DMC_CLTE_RUT_COMP
WHERE A.ID_TIPO_TRANSACCION IN (21,32,36)
GROUP BY B.RUT, B.FECHA;

